### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by 2DU** [kkkyyy03/NamuMarked#16]
오픈나무 개발자 입니다.

만약 파서가 완성 된다면 가져다 써도 되나요?

**Comment by kkkyyy03** [comment]
넵! 어차피 MIT 라이선스니까 마음대로 쓰셔도 괜찮습니다. 최근에 개인적인 일로 좀 바빠서 한동안 손도 못 대고 있긴 하지만요...

언제가 될지는 모르겠지만, 완성한 후에 다시 연락 드리겠습니다.
